aniso8601==8.0.0
certifi==2020.4.5.1
click==7.1.2
Flask==1.1.2
Flask-Cors==3.0.8
Flask-RESTful==0.3.8
gunicorn==20.0.4
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
mkl-fft==1.0.15
mkl-random==1.1.1
mkl-service==2.3.0
numpy==1.18.1
pandas==1.0.3
python-dateutil==2.8.1
pytz==2020.1
six==1.15.0
Werkzeug==1.0.1
wincertstore==0.2
